---
- name: Apt cache should be updated
  apt: update_cache=yes

- name: Install postgres
  apt:
    name:
      - postgresql
      - libpq-dev
      - python-psycopg2

- name: Create Database
  become: yes
  become_user: postgres
  postgresql_db: name={{concourse_database_name}}

- name: Grant user access to database
  become: yes
  become_user: postgres
  postgresql_user: db={{concourse_database_name}} name={{concourse_database_user}} password={{generated_database_password}} priv=ALL

- name: Remove unneccessary privileges
  become: yes
  become_user: postgres
  postgresql_user: name={{concourse_database_user}} role_attr_flags=NOSUPERUSER,NOCREATEDB

- name: Lock database to granted user
  become: yes
  become_user: postgres
  postgresql_privs: db={{concourse_database_name}} role=PUBLIC type=database priv=ALL state=absent

- set_fact:
    concourse_database_password: "{{ generated_database_password }}"
    concourse_database_name: atc
    concourse_database_user: concourse
