---
- name: Apt cache should be updated
  apt: update_cache=yes

- name: Install postgres
  apt:
    name:
      - postgresql
      - libpq-dev
      - python-psycopg2

- name: Generate Credentials
  set_fact:
    concourse_database_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters') }}"
    concourse_database_name: "{{ concourse_database_name }}"
    concourse_database_user: "{{ concourse_database_user }}"

- name: Create Database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ concourse_database_name }}"

- name: Create user
  postgresql_user:
    db: "{{ concourse_database_name }}"
    name: "{{ concourse_database_user }}"
    password: "{{ concourse_database_password }}"

- name: Grant user access to database
  become: yes
  become_user: postgres
  postgresql_user:
    db: "{{ concourse_database_name }}"
    name: "{{ concourse_database_user }}"
    priv: ALL
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: Grant Permissions to user
  become: yes
  become_user: postgres
  postgresql_privs:
    db: "{{ concourse_database_name }}"
    privs: ALL
    type: schema
    objs: public
    role: "{{ concourse_database_user }}"