---

- name: Install Postgresql
  hosts: all
  gather_facts: no

  roles:
    - { role: postgres, tags: 'all' }

- name: Concourse CI Ansible playbook
  hosts: all
  gather_facts: yes
  roles:
    - { role: concourse, tags: 'all' }

