---

- name: Install Postgresql
  hosts: all
  gather_facts: no
  roles:
    - { role: postgres, tags: 'all' }

- name: Concourse CI Web
  hosts: all
  gather_facts: yes
  roles:
    - { role: concourse-web, tags: 'all' }

- name: Concourse CI Worker
  hosts: all
  gather_facts: yes
  roles:
    - { role: concourse-worker, tags: 'all' }

