---

- name: Install Postgresql
  hosts: all
  gather_facts: no

  vars:
    generated_database_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters') }}"

  roles:
    - { role: postgres, tags: 'all' }

- name: Concourse CI Ansible playbook
  hosts: all
  gather_facts: yes
  roles:
    - { role: concourse, tags: 'all' }

